[nrf noup]: zephyr: qt: Remove unistd.h file
fixup! [nrf noup]: zephyr: qt: Add zephyr based control interface

When both unistd.h and net/socket.h are included, compiler
is listing below error for close() declaration.
error: static declaration of 'close' follows non-static declaration

To fix this, remove unistd.h as we need static declaration of
close() from net/socket.h

Signed-off-by: Triveni Danda <triveni.danda@nordicsemi.no>
(cherry picked from commit 36080b692d610ec53cd6b5ed61bca1a81a1b1a90)